//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportingTrainingAPI.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evento()
        {
            this.EventoAtletas = new HashSet<EventoAtleta>();
        }
    
        public int IdEvento { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Local { get; set; }
        public string Estado { get; set; }
        public string Modalidade { get; set; }
        public decimal ValorInscricao { get; set; }
        public System.DateTime TerminoInscricoes { get; set; }
        public System.TimeSpan TempoLimiteEvento { get; set; }
        public string Responsavel { get; set; }
        public string Percurso { get; set; }
        public string Situacao { get; set; }
        public string MotivoCancelamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventoAtleta> EventoAtletas { get; set; }
    }
}
