//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportingTrainingAPI.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SportingTrainingEntities : DbContext
    {
        public SportingTrainingEntities()
            : base("name=SportingTrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Atleta> Atletas { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<EventoAtleta> EventosAtletas { get; set; }
        public virtual DbSet<LoginUsuario> LoginsUsuario { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
